### ISSUE TITLE
Feature: Show a desktop notification when extension is toggled with key shortcut

### ISSUE THREAD

**Issue by tuurep** [AsciiJakob/NoDistractions#11]
I prefer to not have any extension icons on my firefox toolbar, so I have no feedback whether I successfully toggled on using the key shortcut (default: Ctrl+Alt+D)

The extension already can show a notification when using the "Need to quickly check something? You get X minutes" thing.

So I tried extending that for toggling on key shortcut in the fork here:

https://github.com/tuurep/NoDistractions-fork/commit/a8e7b8987673eb8f366a8cde95064f7eae748d15

This is how it looks on my setup:

![image](https://github.com/AsciiJakob/NoDistractions/assets/15036238/a5db4304-4d01-4a86-946b-6cfab4143aa6)

![image](https://github.com/AsciiJakob/NoDistractions/assets/15036238/8e4e5504-2fcd-4897-b88e-8b3140cb1169)

Literally beautiful.

I think it should be only enabled through a setting, because if you have the extension icon on your toolbar, that's already a nice indication of enabled status.

Note:

The way I added the 'correct color' of the NoDistractions icon feels a bit hacky in the code. Although maybe it's not too bad. Thoughts?

Also since I'm adding meaning based on the color of the icon in the notifiation, think about whether the "You get X minutes" -notification's icon color should be green instead of red.

**Comment by AsciiJakob** [comment]
Will have a look today

**Comment by AsciiJakob** [comment]
Oh another thought: Since it's pretty essential for this extension to be accessible in the extension bar (for adding sites, enabling disabling when you don't know the keybind etc), I wonder if there is a way to tell firefox to put it there by default?

**Comment by tuurep** [comment]
Yeah, gotta look into that. It's been so long since I had extensions on the toolbar I'm not sure where they go by default and things like that :)

Also, I used to have them in the "overflow menu", but then they went into the "unified extension menu" (puzzle piece icon) a while back.

**Comment by AsciiJakob** [comment]
> Yeah, gotta look into that. It's been so long since I had extensions on the toolbar I'm not sure where they go by default and things like that :)
> 
> Also, I used to have them in the "overflow menu", but then they went into the "unified extension menu" (puzzle piece icon) a while back.

They seem to go into the puzzle piece icon thing by default and you have to click the cogwheel and then pin extension

**Comment by AsciiJakob** [comment]
I found a manifest option for it and the action bar is now placed by the navigation bar by default as of [63879df](https://github.com/AsciiJakob/NoDistractions/commit/63879dfc95458a12441ff544753e91f94916a45a)
