### ISSUE TITLE
Feature: Setting to hide Close tab -button

### ISSUE THREAD

**Issue by tuurep** [AsciiJakob/NoDistractions#14]
* Although the big button is pretty nice, there are so many ways to close tabs (x on tabs, Ctrl + W, more...), some people might prefer to hide it as unnecessary.
* Since every other 'bottom' element already has an option to be hidden, this one fits right in

Anecdote: I personally mostly use Ctrl+W and [this extension](https://addons.mozilla.org/en-US/firefox/addon/close-tabs-shortcuts/) to close tabs :)

**Comment by AsciiJakob** [comment]
Agreed on feature. While you're at it, I think we should change
`Show the option to disable NoDistractions on the blocked page`to `Show the "<strong>Disable NoDistractions</strong>" button`
and then you could call the new one option:
`Show the "<strong>Close</strong>" button`
